### ISSUE TITLE
Can't specify amazon server security group

### ISSUE THREAD

**Issue by gfxmonk** [pkgcloud/pkgcloud#432]
I can create an image with:

	client.createServer({
		image: 'ami-d2d999ba',
		name: 'test',
		flavor: 't1.micro',
	}, [...]);

But that creates an instance in my default security group. From [amazon/compute/client/servers.js](https://github.com/pkgcloud/pkgcloud/blob/2035bcbc363f1a30d6af59e54faf9de738f5ea63/lib/pkgcloud/amazon/compute/client/servers.js#L155), it looks like I should be able to pass in `SecurityGroup` or `SecurityGroupId` as an additional option, but trying to use either of those throws an error in request validation:

    UnexpectedParameter: Unexpected key 'SecurityGroupId' found in params
    at fail ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/param_validator.js:115:37)
        at validateStructure ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/param_validator.js:50:14)
        at validateMember ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/param_validator.js:61:21)
        at validate ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/param_validator.js:9:10)
        at Request.VALIDATE_PARAMETERS ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/event_listeners.js:88:32)
        at Request.callListeners ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
        at callNextListener ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/sequential_executor.js:90:14)
        at [...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/event_listeners.js:75:9
        at finish ([...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/config.js:228:7)
        at [...]/node_modules/pkgcloud/node_modules/aws-sdk/lib/config.js:244:9

So it seems like the servers.js code doesn't match up with the validations that are applied by aws-sdk.

**Comment by kenperkins** [comment]
hmmm. I'll have to look at this; you may very well be right.

**Comment by gfxmonk** [comment]
Ahh, looks like it's just a multiple / single item thing. The following minimal changes seem to work for me (although you may prefer to extend pkgcloud to take an array, since that's apparently supported by ec2):

    diff --git a/lib/pkgcloud/amazon/compute/client/servers.js b/lib/pkgcloud/amazon/compute/client/servers.js
    index f100651..d2c070a 100644
    --- a/lib/pkgcloud/amazon/compute/client/servers.js
    +++ b/lib/pkgcloud/amazon/compute/client/servers.js
    @@ -154,12 +154,12 @@ exports.createServer = function createServer(options, callback) {
     
       securityGroup = this.securityGroup || options['SecurityGroup'];
       if (securityGroup) {
    -    createOptions['SecurityGroup'] = securityGroup;
    +    createOptions['SecurityGroups'] = [securityGroup];
       }
     
       securityGroupId = this.securityGroupId || options['SecurityGroupId'];
       if (securityGroupId) {
    -    createOptions['SecurityGroupId'] = securityGroupId;
    +    createOptions['SecurityGroupIds'] = [securityGroupId];
       }
     
       createOptions.ImageId = options.image instanceof base.Image

**Comment by kenperkins** [comment]
PRs welcome! :)
