### ISSUE TITLE
Uncaught, unspecified "error" event

### ISSUE THREAD

**Issue by r0t3n** [pkgcloud/pkgcloud#480]
```
[CRIT] [-] [core] Error: Uncaught, unspecified "error" event.
[CRIT] [-] [core]     at Error (native)
[CRIT] [-] [core]     at DestroyableTransform.emit (events.js:87:13)
[CRIT] [-] [core]     at DestroyableTransform.<anonymous> (/root/haraka/node_modules/pkgcloud/lib/pkgcloud/openstack/storage/client/files.js:136:19)
[CRIT] [-] [core]     at DestroyableTransform.emit (events.js:107:17)
[CRIT] [-] [core]     at Request.<anonymous> (/root/haraka/node_modules/pkgcloud/lib/pkgcloud/openstack/client.js:204:23)
[CRIT] [-] [core]     at Request.emit (events.js:107:17)
[CRIT] [-] [core]     at Request.<anonymous> (/root/haraka/node_modules/pkgcloud/node_modules/request/request.js:1057:14)
[CRIT] [-] [core]     at Request.emit (events.js:129:20)
[CRIT] [-] [core]     at IncomingMessage.<anonymous> (/root/haraka/node_modules/pkgcloud/node_modules/request/request.js:998:12)
[CRIT] [-] [core]     at IncomingMessage.emit (events.js:129:20)
```

Tried using 1.1.0 and 1.2.0-alpha.0, used within a custom plugin for haraka where pkgcloud functions are executed within try-catch blocks. Any ideas?

**Comment by r0t3n** [comment]
Fixed, seems something got messed up as the error callback was not being found/called.
