### ISSUE TITLE
TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by gianelc** [pkgcloud/pkgcloud#490]
When trying to get a container via the pkgcloud storage client (getContainer), I have seen the following error:

node_modules/pkgcloud/lib/pkgcloud/openstack/context/identity.js:173
    **else if (!body.access.token.tenant) {
                         ^
TypeError: Cannot read property 'token' of undefined**
    at Request._callback (/home/gianelc/Cisco/Projects/DMP/dmp/node_modules/pkgcloud/lib/pkgcloud/openstack/context/identity.js:173:26)
    at Request.self.callback (/home/gianelc/Cisco/Projects/DMP/dmp/node_modules/pkgcloud/node_modules/request/request.js:123:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/gianelc/Cisco/Projects/DMP/dmp/node_modules/pkgcloud/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/gianelc/Cisco/Projects/DMP/dmp/node_modules/pkgcloud/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
error: Forever detected script exited with code: 1

We are using release 1.2.0-alpha.

**Comment by alieber99** [comment]
Hi gianelc, all, 
I have run into the same issue, has there been any resolution?
