### ISSUE TITLE
Orchestration on OpenStack - Update Stack returns 400

### ISSUE THREAD

**Issue by chenfli** [pkgcloud/pkgcloud#543]
I think it's because you are using the PUT method without the existing=false.

I noticed that there is no Unit/End To End test for updateStack, can you verify it works ?

Create works great, however, update fails with 400 
Unhandled rejection Error: openstack Error (400): Bad Request
    at Request._callback (/usr/src/app/node_modules/pkgcloud/lib/pkgcloud/core/base/client.js:183:28)
    at Request.self.callback (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:123:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:1047:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/pkgcloud/node_modules/request/request.js:998:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by chenfli** [comment]
This happens since not all the attribute of the Stack were initialized,
If I do the following:
stack_to_update.template_url={};
stack_to_update.files={};
stack_to_update.environment={};
openstack.updateStack(stack_to_update)

It will work, I suggest you implement the same logic you did on createStack. You check if this field exists, and if so you set it.
