### ISSUE TITLE
Unable to list containers in Azure Storage

### ISSUE THREAD

**Issue by eman-moh** [pkgcloud/pkgcloud#546]
When I run this small piece of code 
`  var pkgcloud = require('pkgcloud');
  var azure = pkgcloud.storage.createClient({
    provider: 'azure',
    storageAccount: "xx",         // Name of your storage account
    storageAccessKey: "xxxxxxxxxxx" // Access key for storage account
  });

  azure.getContainers(c=>console.log(c));`

I get this error
```

{ Error: azure Error (400): Bad Request
    at Request._callback (~/pkcloud/node_modules/pkgcloud/lib/pkgcloud/core/base/client.js:183:28)
    at Request.self.callback (~/pkcloud/node_modules/request/request.js:123:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (~/pkcloud/node_modules/request/request.js:1047:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (~/pkcloud/node_modules/request/request.js:998:12)
    at emitNone (events.js:91:20)
  name: 'Error',
  provider: 'azure',
  failCode: 'Bad Request',
  statusCode: 400,
  href: 'http://xx.blob.core.windows.net/?comp=list',
  method: 'GET',
  headers: 
   { 'content-length': '328',
     'content-type': 'application/xml',
     server: 'Microsoft-HTTPAPI/2.0',
     'x-ms-request-id': 'b8ba8f95-0001-0085-2b70-548ca0000000',
     date: 'Mon, 12 Dec 2016 12:10:07 GMT',
     connection: 'close' },
  result: { err: '﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:b8ba8f95-0001-0085-2b70-548ca0000000\nTime:2016-12-12T12:10:07.8586867Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2011-08-18</HeaderValue></Error>' } }

```

**Comment by bcoutre** [comment]
Hello, 
on version 1.4 I tried to set the x-ms-version header to 2015-12-11 in line  2048 from file : 
pkgcloud/lib/pkgcloud/azure/utils/constants.js 
TARGET_STORAGE_VERSION: '2015-12-11',
This resolve this error, but bring a new one : 
`{ err: '﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:5f984129-0001-00d5-71a0-655dda000000\nTime:2017-01-03T09:03:34.0610863Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request \'c5mYqHnTQRiQZhx6Ua6LMvlfVyqpjI1w1LZZHepWQ+4=\' is not the same as any computed signature. Server used following string to sign: \'GET\n\n\n\n\n\n\n\n\n\n\n\nx-ms-date:Tue, 03 Jan 2017 09:03:34 GMT\nx-ms-version:2015-12-11\n/ouraccountstorage/ourcontainer\ncomp:list\nrestype:container\'.</AuthenticationErrorDetail></Error>' }`

Any clue ?

**Comment by eman-moh** [comment]
The problem was in the storage deployment type. I created storage with Azure classic deployment models however, when I changed the deployment model to "Azure Resource Manager" it worked well. The difference can be found [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-deployment-model).

**Comment by bcoutre** [comment]
Didn't change whith deployement model, the only way I found was to change @L56  
From : req.headers[HeaderConstants.CONTENT_LENGTH] = '0'; TO req.headers[HeaderConstants.CONTENT_LENGTH] = '1' 
in /lib/pkgcloud/azure/utils/sharedkey.js 
I put 1 but works with others values I didn't test if this interferes on other functions but in my case this is the only one I need.

**Comment by ggondim** [comment]
Experienced the same bug using Azure Storage after migrating from Classic deployment to ARM. Changed both constants `CONTENT_LENGHT` and `TARGET_STORAGE_VERSION`, as specified by @bcoutre and it worked.

I'm wondering when and why this project was abandoned like this. It's been one and a half year since the last reply of this issue. Also, today, 26 PRs pending and some with great enhancements like #616.

I will fork (as the other 321 guys who forked) and commit to this project to solve this bug. But will someone accept the PR?
