### ISSUE TITLE
Getting Error While connecting to openstack storage 

### ISSUE THREAD

**Issue by chetandev** [pkgcloud/pkgcloud#581]
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }

**Comment by tatemz** [comment]
+1 - I am getting this as well

**Comment by rosskukulinski** [comment]
Is your OpenStack cluster leveraging self-signed certificates?  Node.js by default does not allow connecting to untrusted certificates.

You should look at leveraging NODE_TLS_REJECT_UNAUTHORIZED as a process.env to disable the check.  NOTE: From a security perspective, this is not recommended.

**Comment by paulcarroll** [comment]
FWIW adding `strictSSL: false` to the createClient options fixed this
