### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by drzraf** [pkgcloud/pkgcloud#694]
I didn't find, from the documentation, whether running into a browser would be supported (sorry to ask this about a javascript-based project).
In that case, having a UMD build would be really interesting so that we can more easily write browser-based file explorers for Swift & alike.

**Comment by drzraf** [comment]
Here is a sample rollup configuration I tested:

```js
import babel from '@rollup/plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import nodePolyfills from 'rollup-plugin-node-polyfills';
import json from '@rollup/plugin-json';

let plugins = [
    json(),
    resolve({preferBuiltins: true}),
    nodePolyfills(),
    commonjs({
        transformMixedEsModules: true,
        dynamicRequireTargets: [
            'node_modules/pkgcloud/lib/pkgcloud/*',
        ]
    }),
    babel({ babelHelpers: 'bundled' })
];

export default [
    {
        input: 'node_modules/pkgcloud/lib/pkgcloud.js',
        plugins,
        output: {
            name: 'PkgCloud',
            file: 'foo.js',
            sourcemap: false,
            format: 'umd'
	},
    }
];
```

Without polyfills I obtain a monstrous (and non-working) 13 MB build. With polyfill the compilation hits the first errors:

```
bundles node_modules/pkgcloud/lib/pkgcloud.js → foo.js...
[BABEL] Note: The code generator has deoptimised the styling of /project/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
/project/node_modules/pkgcloud/lib/pkgcloud/core (imported by node_modules/pkgcloud/lib/pkgcloud.js)
/project/node_modules/pkgcloud/lib/pkgcloud/core/index.js (imported by /project/node_modules/pkgcloud/lib/pkgcloud/core/index.js?commonjs-external)
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/lodash/lodash.js
17159:     root._ = _;
17160:   }
17161: }.call(this));
              ^
node_modules/async/dist/async.js
3:   typeof define === 'function' && define.amd ? define(['exports'], factory) :
4:   (factory((global.async = global.async || {})));
5: }(this, (function (exports) { 'use strict';
     ^
6: 
7: function slice(arrayLike, start) {
[!] (plugin commonjs) TypeError: Cannot read property 'replace' of undefined
node_modules/pkgcloud/lib/pkgcloud/azure/utils/hmacsha256sign.js
TypeError: Cannot read property 'replace' of undefined
    at Object.makeLegalIdentifier (/project/node_modules/@rollup/pluginutils/dist/cjs/index.js:347:10)
    at deconflict (/project/node_modules/@rollup/plugin-commonjs/dist/index.js:330:34)
    at transformCommonjs (/project/node_modules/@rollup/plugin-commonjs/dist/index.js:942:32)
    at Object.transformAndCheckExports (/project/node_modules/@rollup/plugin-commonjs/dist/index.js:1312:12)
    at Object.transform (/project/node_modules/@rollup/plugin-commonjs/dist/index.js:1404:41)
    at /project/node_modules/rollup/dist/shared/rollup.js:18733:25
```

**Comment by drzraf** [comment]
2021 ping? :)
